;/*
;**********************************************************************************************************************
;*											        eGon
;*						           the Embedded GO-ON Bootloader System
;*									         eGON boot sub-system
;*
;*						  Copyright(C), 2006-2010, SoftWinners Microelectronic Co., Ltd.
;*                                           All Rights Reserved
;*
;* File    : eGon2.h
;*
;* By      : Jerry
;*
;* Version : V2.00
;*
;* Date	  :
;*
;* Descript:
;**********************************************************************************************************************
;*/


    IF :LNOT::DEF:__EGON2_INC_
	GBLA  __EGON2_INC_

    include cfgs\arm_a8.inc
    include arch\ebios.inc




    endif
    end



